In [18]:
import pandas as pd
import keras 
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import pydot
import graphviz
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot
from keras.utils import plot_model
import seaborn as sns
import numpy as np

In [19]:
dataset = pd.read_csv('iris.csv')
dataset.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [20]:
dataset.drop(['Id'], axis=1)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [21]:
X = dataset.iloc[:,0:4].values
y = dataset.iloc[:,5].values

In [22]:
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [23]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

y1 = encoder.fit_transform(y)
Y = pd.get_dummies(y1).values

from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2, random_state=0)

In [24]:
y1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [25]:
Y

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [26]:
model = Sequential()

model.add(Dense(4,input_shape=(4,), activation='relu'))
model.add(Dense(5, activation='relu'))

model.add(Dense(3, activation='softmax'))

In [27]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 4)                 20        
_________________________________________________________________
dense_4 (Dense)              (None, 5)                 25        
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 18        
Total params: 63
Trainable params: 63
Non-trainable params: 0
_________________________________________________________________


In [28]:
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics= ['accuracy'])

In [36]:
model.fit(X_train,y_train, batch_size=2, epochs=500)

Epoch 1/500
60/60 [==============================] - 0s 559us/step - loss: 3.0001e-04 - accuracy: 1.0000
Epoch 2/500
60/60 [==============================] - 0s 499us/step - loss: 2.8862e-04 - accuracy: 1.0000
Epoch 3/500
60/60 [==============================] - 0s 515us/step - loss: 2.9358e-04 - accuracy: 1.0000
Epoch 4/500
60/60 [==============================] - 0s 515us/step - loss: 2.8848e-04 - accuracy: 1.0000
Epoch 5/500
60/60 [==============================] - 0s 532us/step - loss: 2.9879e-04 - accuracy: 1.0000
Epoch 6/500
60/60 [==============================] - 0s 549us/step - loss: 2.7893e-04 - accuracy: 1.0000
Epoch 7/500
60/60 [==============================] - 0s 499us/step - loss: 3.0025e-04 - accuracy: 1.0000
Epoch 8/500
60/60 [==============================] - 0s 515us/step - loss: 3.0040e-04 - accuracy: 1.0000
Epoch 9/500
60/60 [==============================] - 0s 515us/step - loss: 3.0063e-04 - accuracy: 1.0000
Epoch 10/500
60/60 [==============================] - 0

60/60 [==============================] - 0s 499us/step - loss: 2.3279e-04 - accuracy: 1.0000
Epoch 79/500
60/60 [==============================] - 0s 515us/step - loss: 2.2693e-04 - accuracy: 1.0000
Epoch 80/500
60/60 [==============================] - 0s 499us/step - loss: 2.5158e-04 - accuracy: 1.0000
Epoch 81/500
60/60 [==============================] - 0s 549us/step - loss: 2.6103e-04 - accuracy: 1.0000
Epoch 82/500
60/60 [==============================] - 0s 515us/step - loss: 2.2000e-04 - accuracy: 1.0000
Epoch 83/500
60/60 [==============================] - 0s 499us/step - loss: 2.5339e-04 - accuracy: 1.0000
Epoch 84/500
60/60 [==============================] - 0s 515us/step - loss: 2.4133e-04 - accuracy: 1.0000
Epoch 85/500
60/60 [==============================] - 0s 499us/step - loss: 2.6373e-04 - accuracy: 1.0000
Epoch 86/500
60/60 [==============================] - 0s 515us/step - loss: 2.7171e-04 - accuracy: 1.0000
Epoch 87/500
60/60 [==============================] - 0s 49

60/60 [==============================] - 0s 565us/step - loss: 2.9736e-04 - accuracy: 1.0000
Epoch 156/500
60/60 [==============================] - 0s 499us/step - loss: 2.8119e-04 - accuracy: 1.0000
Epoch 157/500
60/60 [==============================] - 0s 499us/step - loss: 2.5935e-04 - accuracy: 1.0000
Epoch 158/500
60/60 [==============================] - 0s 515us/step - loss: 2.9670e-04 - accuracy: 1.0000
Epoch 159/500
60/60 [==============================] - 0s 515us/step - loss: 2.7804e-04 - accuracy: 1.0000
Epoch 160/500
60/60 [==============================] - 0s 499us/step - loss: 2.5962e-04 - accuracy: 1.0000
Epoch 161/500
60/60 [==============================] - 0s 499us/step - loss: 3.0126e-04 - accuracy: 1.0000
Epoch 162/500
60/60 [==============================] - 0s 499us/step - loss: 2.9651e-04 - accuracy: 1.0000
Epoch 163/500
60/60 [==============================] - 0s 532us/step - loss: 3.2370e-04 - accuracy: 1.0000
Epoch 164/500
60/60 [==============================

60/60 [==============================] - 0s 515us/step - loss: 1.7197e-04 - accuracy: 1.0000
Epoch 232/500
60/60 [==============================] - 0s 515us/step - loss: 1.7092e-04 - accuracy: 1.0000
Epoch 233/500
60/60 [==============================] - 0s 499us/step - loss: 1.8653e-04 - accuracy: 1.0000
Epoch 234/500
60/60 [==============================] - 0s 515us/step - loss: 1.8380e-04 - accuracy: 1.0000
Epoch 235/500
60/60 [==============================] - 0s 499us/step - loss: 1.8023e-04 - accuracy: 1.0000
Epoch 236/500
60/60 [==============================] - 0s 515us/step - loss: 1.7993e-04 - accuracy: 1.0000
Epoch 237/500
60/60 [==============================] - 0s 499us/step - loss: 1.8021e-04 - accuracy: 1.0000
Epoch 238/500
60/60 [==============================] - 0s 499us/step - loss: 1.7716e-04 - accuracy: 1.0000
Epoch 239/500
60/60 [==============================] - 0s 499us/step - loss: 1.6896e-04 - accuracy: 1.0000
Epoch 240/500
60/60 [==============================

60/60 [==============================] - 0s 499us/step - loss: 0.0495 - accuracy: 0.9917
Epoch 309/500
60/60 [==============================] - 0s 515us/step - loss: 0.0515 - accuracy: 1.0000
Epoch 310/500
60/60 [==============================] - 0s 515us/step - loss: 0.0490 - accuracy: 1.0000
Epoch 311/500
60/60 [==============================] - 0s 499us/step - loss: 0.0514 - accuracy: 0.9833
Epoch 312/500
60/60 [==============================] - 0s 515us/step - loss: 0.0480 - accuracy: 1.0000
Epoch 313/500
60/60 [==============================] - 0s 515us/step - loss: 0.0552 - accuracy: 0.9917
Epoch 314/500
60/60 [==============================] - 0s 499us/step - loss: 0.0476 - accuracy: 0.9917
Epoch 315/500
60/60 [==============================] - 0s 515us/step - loss: 0.0520 - accuracy: 0.9917
Epoch 316/500
60/60 [==============================] - 0s 565us/step - loss: 0.0508 - accuracy: 0.9917
Epoch 317/500
60/60 [==============================] - 0s 515us/step - loss: 0.0470 - a

60/60 [==============================] - 0s 549us/step - loss: 0.0414 - accuracy: 0.9833
Epoch 388/500
60/60 [==============================] - 0s 565us/step - loss: 0.0458 - accuracy: 0.9833
Epoch 389/500
60/60 [==============================] - 0s 515us/step - loss: 0.0480 - accuracy: 0.9833
Epoch 390/500
60/60 [==============================] - 0s 515us/step - loss: 0.0393 - accuracy: 0.9917
Epoch 391/500
60/60 [==============================] - 0s 515us/step - loss: 0.0403 - accuracy: 0.9917
Epoch 392/500
60/60 [==============================] - 0s 499us/step - loss: 0.0364 - accuracy: 0.9917
Epoch 393/500
60/60 [==============================] - 0s 499us/step - loss: 0.0444 - accuracy: 0.9917
Epoch 394/500
60/60 [==============================] - 0s 515us/step - loss: 0.0406 - accuracy: 0.9917
Epoch 395/500
60/60 [==============================] - 0s 499us/step - loss: 0.0376 - accuracy: 1.0000
Epoch 396/500
60/60 [==============================] - 0s 515us/step - loss: 0.0473 - a

60/60 [==============================] - 0s 499us/step - loss: 0.0245 - accuracy: 1.0000
Epoch 467/500
60/60 [==============================] - 0s 499us/step - loss: 0.0314 - accuracy: 1.0000
Epoch 468/500
60/60 [==============================] - 0s 515us/step - loss: 0.0291 - accuracy: 1.0000
Epoch 469/500
60/60 [==============================] - 0s 515us/step - loss: 0.0265 - accuracy: 1.0000
Epoch 470/500
60/60 [==============================] - 0s 549us/step - loss: 0.0292 - accuracy: 1.0000
Epoch 471/500
60/60 [==============================] - 0s 515us/step - loss: 0.0275 - accuracy: 1.0000
Epoch 472/500
60/60 [==============================] - 0s 499us/step - loss: 0.0246 - accuracy: 1.0000
Epoch 473/500
60/60 [==============================] - 0s 515us/step - loss: 0.0289 - accuracy: 1.0000
Epoch 474/500
60/60 [==============================] - 0s 499us/step - loss: 0.0259 - accuracy: 1.0000
Epoch 475/500
60/60 [==============================] - 0s 515us/step - loss: 0.0298 - a

In [37]:
y_pred = model.predict(X_test)
y_test_class = np.argmax(y_test, axis=1)
y_pred_class = np.argmax(y_pred, axis=1)

In [38]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class, y_pred_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00         6

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
